### PR TITLE
Added Queens and Sudoku

### PR DESCRIPTION
**Pull request by atharvanaphade**

### CODE REVIEW

**Comment by gauravghati** [comment]
There is a syntax error in your "chess-queens.cpp", making n as a const variable will resolve it, update it and make the PR again

**Comment by atharvanaphade** [comment]
> There is a syntax error in your "chess-queens.cpp", making n as a const variable will resolve it, update it and make the PR again

done

**Comment by gauravghati** [comment]
still not working, make sure to run it before you commit.

**Comment by atharvanaphade** [comment]
> still not working, make sure to run it before you commit.

fixed now, everything is working, also added fibonacci sequence using recursion

**Pull request merged**
